name: Templating

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  templating:
    if: github.run_number == 1 && github.repository != 'DEFRA/cdp-node-frontend-template'
    name: CDP-templating-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Ensure apply.sh has correct line endings
        run: |
          sed -i 's/\r$//' .github/template/apply.sh
      - name: Apply template
        run: bash .github/template/apply.sh ${{ github.repository }}
      - name: Cleanup
        run: bash .github/template/cleanup.sh
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add -A
          git commit -m "Applying template changes"
          git push origin main